// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Lab5ProjML.Model
{
    public class ModelInput
    {
        [ColumnName("age"), LoadColumn(0)]
        public float Age { get; set; }


        [ColumnName("gender"), LoadColumn(1)]
        public float Gender { get; set; }


        [ColumnName("cp"), LoadColumn(2)]
        public float Cp { get; set; }


        [ColumnName("restbps"), LoadColumn(3)]
        public float Restbps { get; set; }


        [ColumnName("chol"), LoadColumn(4)]
        public float Chol { get; set; }


        [ColumnName("fbs"), LoadColumn(5)]
        public float Fbs { get; set; }


        [ColumnName("restecg"), LoadColumn(6)]
        public float Restecg { get; set; }


        [ColumnName("mhra"), LoadColumn(7)]
        public float Mhra { get; set; }


        [ColumnName("exang"), LoadColumn(8)]
        public float Exang { get; set; }


        [ColumnName("oldpeak"), LoadColumn(9)]
        public float Oldpeak { get; set; }


        [ColumnName("slope"), LoadColumn(10)]
        public float Slope { get; set; }


        [ColumnName("cf"), LoadColumn(11)]
        public float Cf { get; set; }


        [ColumnName("thal"), LoadColumn(12)]
        public float Thal { get; set; }


        [ColumnName("disease"), LoadColumn(13)]
        public string Disease { get; set; }


    }
}
