// This file was auto-generated by ML.NET Model Builder. 

using System;
using Lab5ProjML.Model;

namespace Lab5ProjML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Age = 52F,
                Gender = 1F,
                Cp = 0F,
                Restbps = 125F,
                Chol = 212F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Disease with predicted Disease from sample data...\n\n");
            Console.WriteLine($"Age: {sampleData.Age}");
            Console.WriteLine($"Gender: {sampleData.Gender}");
            Console.WriteLine($"Cp: {sampleData.Cp}");
            Console.WriteLine($"Restbps: {sampleData.Restbps}");
            Console.WriteLine($"Chol: {sampleData.Chol}");
            Console.WriteLine($"\n\nPredicted Disease value {predictionResult.Prediction} \nPredicted Disease scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
